lr: 0.0005
weight_decay: 0.005

net:
  class_path: src.models.components.vit_simple.VisionTransformerSimple
  init_args:
    img_size: [128, 256]
    patch_size: 16
    in_vars: ['2m_temperature', '10m_u_component_of_wind', '10m_v_component_of_wind']
    embed_dim: 1024
    depth: 8
    num_heads: 16
    mlp_ratio: 4
    out_vars: ['2m_temperature_max', '10m_u_component_of_wind_max', '10m_v_component_of_wind_max']
pretrained_path: ''
# img_size=224, patch_size=16, in_chans=3,
# embed_dim=1024, depth=24, num_heads=16,
# decoder_embed_dim=512, decoder_depth=8, decoder_num_heads=16,
# mlp_ratio=4., norm_layer=nn.LayerNorm, norm_pix_loss=False
