# Documentation:
# https://amulet-docs.azurewebsites.net/main/advanced/51_distributed.html#
# https://amulet-docs.azurewebsites.net/config_file.html

description: Download ERA5

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: ml_template:latest

target:
  service: aml
  name: d8-ded

storage:
  data_write:
    storage_account_name: weatherdatastorage2
    # storage_account_name: weatherml1836488272
    container_name: datasets
    mount_dir: /mnt/data_write
    is_output: True

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
  # amlt run jobs/amlt.yaml --target-name V100-1x-ded :train_1_node_1_gpu ml-template-mnist
  - name: download_era5
    sku: 1xC8
    submit_args:
      container_args:
        shm_size: 650g
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
    command:
      # - touch /mnt/data_write/test.txt
      # - echo $$AMLT_OUTPUT_DIR
      - wget --no-check-certificate "https://dataserv.ub.tum.de/s/m1524895/download?path=%2F&files=1.40625deg&downloadStartSecret=ivy85gdd6mh" -O /mnt/data_write/1.40625deg.zip
      # - wget --no-check-certificate "https://dataserv.ub.tum.de/s/m1524895/download?files=desktop.ini" -O /mnt/data_write/desktop.ini
