# Documentation:
# https://amulet-docs.azurewebsites.net/main/advanced/51_distributed.html#
# https://amulet-docs.azurewebsites.net/config_file.html

description: Download ERA5

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: ml_template:latest
  # image_setup:
  #   - sudo apt-get install rsync grsync
  # - pip install capi
  #- pip install -e .

target:
  service: aml
  name: d8-ded

# $CONFIG_DIR is expanded to the directory of this config file.
code:
  local_dir: $CONFIG_DIR/../

storage:
  output:
    storage_account_name: weathermlstorage
    container_name: datasets
    mount_dir: /mnt/data
    mount_options: ["--file-cache-timeout-in-seconds=0"]

# SKU usage: G1 (single GPU), G4 (quad GPU), G4-V100 (1 machine, 4 V100 gpus), etc...
jobs:
  # amlt run jobs/amlt.yaml --target-name V100-1x-ded :train_1_node_1_gpu ml-template-mnist
  - name: download_era5
    sku: 1xC8
    submit_args:
      container_args:
        shm_size: 650g
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
    command:
      - touch /mnt/data/test.txt
      # - echo $$AMLT_OUTPUT_DIR
      # - wget --no-check-certificate "https://dataserv.ub.tum.de/s/m1524895/download?path=%2F&files=IFS_T63&downloadStartSecret=rklt0z2f0r" -O echo $$AMLT_OUTPUT_DIR/ifs_t63.zip
