# Documentation:
# https://amulet-docs.azurewebsites.net/main/advanced/51_distributed.html#
# https://amulet-docs.azurewebsites.net/config_file.html

description: Single GPU training for MAE

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: climate_pretraining:latest

code:
  local_dir: $CONFIG_DIR/../

target:
  service: aml
  name: v100-1-ded

storage:
  data:
    storage_account_name: weatherdatastorage2
    # storage_account_name: weatherml1836488272
    container_name: datasets
    mount_dir: /mnt/data
    mount_options: ["--file-cache-timeout-in-seconds=0"]

# some environment variables to ease up setting of jobs
env_defaults:
  NODES: 1
  GPUS: 1

jobs:
  - name: pretrain_17_variables
    sku: ${NODES}x32G${GPUS} # ex: G1
    command:
      - pip install -e .
      - export MKL_THREADING_LAYER=GNU
      - python src/train_mae2.py --config configs/train_mae.yaml --model.reconstruct_all=True --data.root_dir=/mnt/data/1.40625deg_monthly_np --data.reader=npy
