# Documentation:
# https://amulet-docs.azurewebsites.net/main/advanced/51_distributed.html#
# https://amulet-docs.azurewebsites.net/config_file.html

description: Multi GPU training for MAE

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: climate_pretraining:latest

code:
  local_dir: $CONFIG_DIR/../

target:
  service: aml
  name: v100x4-ded

storage:
  data:
    storage_account_name: weatherdatastorage2
    # storage_account_name: weatherml1836488272
    container_name: datasets
    mount_dir: /mnt/data
    mount_options: ["--file-cache-timeout-in-seconds=0"]

# some environment variables to ease up setting of jobs
env_defaults:
  NODES: 1
  GPUS: 4

jobs:
  - name: mae_4gpus_64x4bz_2worker_10000buffer_monthly
    sku: ${NODES}x32G${GPUS} # ex: G1
    submit_args:
      container_args:
        shm_size: 650g
    command:
      - pip install -e .
      - export MKL_THREADING_LAYER=GNU
      - python src/train_mae2.py --config configs/train_mae.yaml
                      --trainer.strategy=ddp --trainer.devices=${GPUS}
                      --model.reconstruct_all=True
                      --data.root_dir=/mnt/data/1.40625deg_monthly_np --data.reader=npy --data.num_workers=2 --data.batch_size=64 --data.buffer_size=10000
