# Documentation:
# https://amulet-docs.azurewebsites.net/main/advanced/51_distributed.html#
# https://amulet-docs.azurewebsites.net/config_file.html

description: Extracting yearly npz files

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: climate_pretraining:latest

code:
  local_dir: $CONFIG_DIR/../

target:
  service: aml
  name: d14ded

storage:
  my_data:
    storage_account_name: weatherdatastorage2
    # storage_account_name: weatherml1836488272
    container_name: datasets
    mount_dir: /mnt/data
    is_output: True

# some environment variables to ease up setting of jobs
# env_defaults:
#   NODES: 2
#   GPUS: 1

# jobs:
#   # amlt run jobs/amlt.yaml --target-name V100-1x-ded :train_1_node_1_gpu ml-template-mnist
#   - name: extract_npy
#     sku: ${NODES}x32G${GPUS} # ex: G1
#     submit_args:
#       container_args:
#         shm_size: 650g
#       env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
#     command:
#       - echo $$AMLT_OUTPUT_DIR

jobs:
  - name: extract_npz
    sku: 1xC16
    command:
      #- conda env create --file docker/environment.yml
      # - export PYTHONPATH=$PWD
      # - echo $PYTHONPATH
      #- conda activate climate_pretrain
      #/opt/miniconda/envs/ml_template/bin/python src/train_mae.py --config configs/train_mae.yaml --data.root=/mnt/data/1.40625deg --data.num_workers=4 --trainer.default_root_dir=$$AMLT_OUTPUT_DIR --model.reconstruct_all={reconstruct}
      - python src/nc2np.py /mnt/data/1.40625deg

