# Documentation:
# https://amulet-docs.azurewebsites.net/main/advanced/51_distributed.html#
# https://amulet-docs.azurewebsites.net/config_file.html

description: Extracting equally npz files

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: climate_pretraining:latest

code:
  local_dir: $CONFIG_DIR/../

target:
  service: aml
  name: f72-ded

storage:
  my_data:
    storage_account_name: weatherdatastorage2
    # storage_account_name: weatherml1836488272
    container_name: datasets
    mount_dir: /mnt/data
    is_output: True

jobs:
  - name: extract_equally_npz_cmcc
    sku: 1xC72
    command:
      # - python src/nc2np_equally_cmip6_mpi.py /mnt/data/CMIP6/MPI-ESM/5.625deg --num_shards=10
      # - python src/nc2np_equally_cmip6_taiesm1.py /mnt/data/CMIP6/TaiESM1/5.625deg --num_shards=20
      # - python src/nc2np_equally_cmip6_awi.py /mnt/data/CMIP6/AWI-ESM/5.625deg --num_shards=2
      # - python src/nc2np_equally_cmip6_hammoz.py /mnt/data/CMIP6/HAMMOZ/5.625deg --num_shards=40
      - python src/nc2np_equally_cmip6_cmcc.py /mnt/data/CMIP6/CMCC/5.625deg --num_shards=2
      # - python src/nc2np_equally_cmip6_nasa.py /mnt/data/CMIP6/NASA-GISS/5.625deg --num_shards=2
