# Documentation:
# https://amulet-docs.azurewebsites.net/main/advanced/51_distributed.html#
# https://amulet-docs.azurewebsites.net/config_file.html

description: Single GPU training for ViT with only 3 variables

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: climate_pretraining:latest

code:
  local_dir: $CONFIG_DIR/../

target:
  service: aml
  name: v100-1-ded

storage:
  data:
    storage_account_name: weatherdatastorage2
    # storage_account_name: weatherml1836488272
    container_name: datasets
    mount_dir: /mnt/data
    mount_options: ["--file-cache-timeout-in-seconds=0"]

# some environment variables to ease up setting of jobs
env_defaults:
  NODES: 1
  GPUS: 1

jobs:
  - name: tokenized_vit_finetune_videomae_0.9_5.625deg_direct_5days_freeze
    sku: ${NODES}x32G${GPUS} # ex: G1
    submit_args:
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
      container_args:
        shm_size: 650g
    command:
      - pip install -e .
      - export MKL_THREADING_LAYER=GNU
      - python src/train_vit2.py --config configs/train_tokenized_vit.yaml
        --trainer.devices=${GPUS}
        --data.root_dir=/mnt/data/5.625deg_equally_np --data.reader=npy --data.variables=['z','t'] --data.num_workers=1 --data.predict_range=120 --data.predict_steps=1 --data.batch_size=128
        --model.net.in_vars=['geopotential_1000','geopotential_850','geopotential_500','geopotential_50','temperature_850','temperature_500']
        --model.net.learn_pos_emb=True
        --model.net.img_size=[32,64]
        --model.pretrained_path=/mnt/data/checkpoints/tokenized_video_mae/5.625deg/last.ckpt
        --model.net.freeze_encoder=True
