# Documentation:
# https://amulet-docs.azurewebsites.net/main/advanced/51_distributed.html#
# https://amulet-docs.azurewebsites.net/config_file.html

description: Single GPU training for ViT with only 3 variables

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: climate_pretraining:latest

code:
  local_dir: $CONFIG_DIR/../

target:
  service: aml
  name: v100x4ssh-sc

storage:
  data:
    storage_account_name: weatherdatastorage2
    # storage_account_name: weatherml1836488272
    container_name: datasets
    mount_dir: /mnt/data
    mount_options: ["--file-cache-timeout-in-seconds=0"]

# some environment variables to ease up setting of jobs
env_defaults:
  NODES: 1
  GPUS: 4

jobs:
  - name: tokenized_vit_finetune_vit_cmip6_freeze
    sku: ${NODES}x32G${GPUS} # ex: G1
    submit_args:
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
      container_args:
        shm_size: 650g
    command:
      - pip install -e .
      - export MKL_THREADING_LAYER=GNU
      - python src/train_vit2.py --config configs/train_tokenized_vit.yaml
        --trainer.strategy=ddp --trainer.devices=${GPUS}
        --data.root_dir=/mnt/data/1.40625deg_equally_np --data.reader=npy --data.variables=['t2m','u10','v10'] --data.num_workers=2 --data.predict_range=6 --data.predict_steps=4 --data.batch_size=32
        --model.net.in_vars=['2m_temperature','10m_u_component_of_wind','10m_v_component_of_wind']
        --model.net.learn_pos_emb=True
        --model.pretrained_path=/mnt/data/checkpoints/vit/vit_cmip6/last.ckpt
        --model.net.freeze_encoder=True
