seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  gpus: 1
  num_nodes: 1
  accelerator: gpu
  strategy: ddp_find_unused_parameters_false

# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.0005
  weight_decay: 0.005
  warmup_epochs: 5
  max_epochs: 30
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  mask_ratio: 0.75
  reconstruct_all: False

  net:
    class_path: src.models.components.tokenized_video_mae.TokenizedVideoMAE
    init_args:
      timesteps: 4
      img_size: [128, 256]
      patch_size: 16
      learn_pos_emb: False
      in_vars:
        [
          "2m_temperature",
          "10m_u_component_of_wind",
          "10m_v_component_of_wind",
        ]
      embed_dim: 1024
      depth: 8
      num_heads: 16
      decoder_embed_dim: 512
      decoder_depth: 4
      decoder_num_heads: 16
      out_vars: null
      mlp_ratio: 4
      norm_pix_loss: False

# ---------------------------- DATA -------------------------------------------
data:
  root_dir: /datadrive/1.40625deg_equally_np
  reader: npy # npy or zarr
  dataset_type: video # pretrain or forecast (finetune)
  variables: ["t2m", "u10", "v10"]
  timesteps: 4
  buffer_size: 20000
  batch_size: 128
  num_workers: 1
  pin_memory: False
