variable_data_paths:
  [
    "/mnt/weatherbench/temperature_2m.npy",
    "/mnt/weatherbench/wind_u_10m.npy",
    "/mnt/weatherbench/wind_v_10m.npy",
  ]
train_val_test_split: [300000, 25000, 25640]
normalize: True
batch_size: 128
num_workers: 2
pin_memory: False
