variable_data_paths:
  [
    "/mnt/weatherbench/temperature_2m.npy",
    "/mnt/weatherbench/wind_u_10m.npy",
    "/mnt/weatherbench/wind_v_10m.npy",
  ]
predict_range: 6
train_val_test_split: [45000, 5000, 8439]
normalize: False
batch_size: 128
num_workers: 2
pin_memory: False
