variable_data_paths:
  [
    "/mnt/weatherbench/temperature_2m.npy",
    "/mnt/weatherbench/wind_u_10m.npy",
    "/mnt/weatherbench/wind_v_10m.npy",
  ]
predict_range: 6
train_val_test_split: [54056, 2924, 1459]
normalize: True
batch_size: 128
num_workers: 2
pin_memory: False
