root: /mnt/weatherbench
variables:
  [
    "2m_temperature",
    "10m_u_component_of_wind",
    "10m_v_component_of_wind",
  ]
predict_range: 6
train_val_test_split: [54056, 2924, 1459]
transforms:
  class_path: torchvision.transforms.Normalize
  init_args:
    mean: [277.0595, -0.05025468, 0.18755548]
    std: [21.289722, 5.5454874, 4.764006]
batch_size: 128
num_workers: 2
pin_memory: False
